name: Sync to Huggingface

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Log in to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: huggingface-cli login --token $HF_TOKEN

      - name: Sync to Huggingface
        uses: nateraw/huggingface-sync-action@v0.0.5
        with:
          github_repo_id: 'dlzcods/eye-disease-classification'
          huggingface_repo_id: 'dielz/xenon-001'
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: 'model'
          private: false
